Creator_Database_Project/Creator_Database_Project/urls.py
from django.contrib import admin
from django.urls import path, include 

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('creator_dashboard.urls')),
    # path('upload.php/', )
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Creator_Database_Project/creator_dashboard/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name="home"),

    path('newTemplate/', views.formPage, name="newTemplate"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Creator_Database_Project/creator_dashboard/models.py
from django.db import models

# Create your models here.

class Creator(models.Model):
    name = models.CharField(max_length=200, null=True)
    upload = models.FileField(null=True)

Creator_Database_Project/creator_dashboard/forms.py
from django import forms
from .models import Creator

class CreatorForm(forms.ModelForm):

    class Meta:
        model = Creator
        fields = ["name","upload"]

Creator_Database_Project/creator_dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import CreatorForm

# Create your views here.
from .models import *

def home(request):
    creators = Creator.objects.all()
    return render(request, 'accounts/dashboard.html', {'creators': creators})




def formPage(request):
    # vuln = get_object_or_404(Vuln, pk=pk)
    if request.method == "POST":
        r_form = CreatorForm(request.POST, request.FILES)
        print(request.FILES)
        print(request)
        if r_form.is_valid():
            Creator.objects.all().delete()
            view_form = r_form.save(commit=False)
            view_form.save()
            return redirect("home")
        else: 
            print("this is not valid")
    else:
        r_form = CreatorForm()
    context = dict(form=r_form)
    template = 'accounts/newTemplate.html'
    return render(request, template, context)

# def changeName(request):
#     context = {}
#     return render(request, 'accounts/dashboard.html', context)
    

# def uploadPic(request):
#     context = {}
#     return render(request, 'accounts/dashboard.html', context)

Creator_Database_Project/creator_dashboard/templates/accounts/dashboard.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta charset="utf-8">
  <title>Content Creator Dashboard</title>
</head>
<body>

  <p class="row" style="padding-left: 60px;"> &nbsp; </p>
  <!-- Deliberatley empty space -->

    <h1 class="row" style="padding-left: 60px;">Welcome to your Content Creator Dashboard!</h1>

    <p class="row"> &nbsp; </p>
    <!-- Deliberatley empty space -->

    <p class="row" style="padding-left: 60px;">Your current displayname is: 

      {% for i in creators %}
          {{i.name}}
      {% endfor %}

    </p>

    <a style="padding-left: 60px" href="./newTemplate">Click here </a>if you would like to change your displayname or your profile picture.

</body>
</html>

Creator_Database_Project/creator_dashboard/templates/accounts/different.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta charset="utf-8">
</head>
<body>

<form method="POST" class="form-group">
    {% csrf_token %}
    <legend class="border-bottom mb-4">Update or Change your Username: </legend>
    <div class="form-group">
        <button class="btn" type="submit">Post</button>
    </div>

    <div id="div_id_name" class="form-group">
        <label for="id_name" class="requiredField">"Name"<span class="asteriskField">*</span></label>
        <input type="text" name="name" maxlength="200" class="textinput textInput form-control" required id="id_name">
    </div>

    <div id="div_id_upload" class="form-group">
        <label for="id_upload" class> Upload </label>
        <input type="file" name="upload" accept="image/*" class="clearablefileinput form-control-file" id="id_upload">
        <input type="submit" value="Upload Image" name="submit">
    </div>

</form>


</body>
</html>

Creator_Database_Project/creator_dashboard/templates/accounts/newTemplate.html
<!-- This is the template associated with the URL 'form_page'!!! -->
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta charset="utf-8">
  <title>Content Creator Dashboard</title>
</head>
<body>

{% load crispy_forms_tags %}

<!-- {% block content %} -->
  <div class="container">
    <form method="POST" class="form-group" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Update or Change Your Username: </legend>
        {{ form|crispy }}
        <button class="btn" type="submit">Post</button>
      </fieldset>

    </form>
  </div>
<!-- {% endblock %} -->

</body>
</html>